name: Deploy HTML Page

on:
  push:
    branches:
      - main  # This will trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the main branch

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"  # Set user name for Git commit
        git config user.email "github-actions[bot]@users.noreply.github.com"  # Set user email

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Action to deploy the page
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the action
        publish_dir: ./SimpleWebApp  # The directory to deploy; ./ means the root of your repo
